version: '3'

tasks:
  up:
    desc: Creates a complete Azure ML environment 
    cmds:
    - terraform workspace new {{.APP}} || true
    - terraform workspace select {{.APP}}
    - terraform init
    - task: apply
    vars: 
      APP: '{{default .CLI_ARGS}}'  
      
  apply:
    cmds:
    - terraform apply -auto-approve -var "app_name={{.APP}}" -compact-warnings
    vars: 
      APP: '{{default .CLI_ARGS}}'

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info
    - az group delete -n {{.RG}} --yes || true
    vars:
      RG: 
        sh: terraform  output -raw APP_RESOURCE_GROUP
